# NumPy

Read the links: https://numpy.org/doc/stable/user/quickstart.html  and https://numpy.org/doc/stable/user/basics.broadcasting.html  before solving the exercises. 

In [2]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [5]:
A = np.arange(1, 16).reshape(3,5)

In [3]:
A.ndim

2

In [12]:
A.shape

(3, 5)

In [ ]:
A.itemsize

8

In [ ]:
A.dtype.name

'int64'

### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [ ]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)
print()
D = np.subtract(B,C) # = B - C
E = np.multiply(B,C) # = B * C
F=(B@C)
print('Elementwise subtraction.')
print(D)
print('Elementwise multiplication.')
print(E)
print(' Matrix multiplication')
print(F)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise subtraction.
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]
* Elementwise multiplication.
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]
 Matrix multiplication
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]


### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column. 

In [12]:
B = np.arange(1, 10).reshape(3, 3)
print(B)
print('* Exponentiate each number elementwise (use the np.exp function).')
print(np.exp(B))

print('Calculate the minimum value in the whole matrix.')
print(np.min(B))
print('* Calculcate the minimum value in each row.')
print(np.min(B, axis=1))

print(' Calculcate the minimum value in each column.')
print(np.min(B, axis=0))

print('Find the index value for the minimum value in the whole matrix')
print(np.argmin(B))
print('Find the index value for the minimum value in each row ')
print(np.argmin(B, axis=1))

print('Calculate the sum for all elements.')
print(np.sum(B))
print('* Calculate the mean for each column.')
print(np.mean(B,axis=0))
print('Calculate the median for each column. ')
print(np.median(B, axis=0))



[[1 2 3]
 [4 5 6]
 [7 8 9]]
* Exponentiate each number elementwise (use the np.exp function).
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]
Calculate the minimum value in the whole matrix.
1
* Calculcate the minimum value in each row.
[1 4 7]
 Calculcate the minimum value in each column.
[1 2 3]
Find the index value for the minimum value in the whole matrix
0
Find the index value for the minimum value in each row 
[0 0 0]
Calculate the sum for all elements.
45
* Calculate the mean for each column.
[4. 5. 6.]
Calculate the median for each column. 
[4. 5. 6.]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [16]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [6]:
A[1]

array([ 6,  7,  8,  9, 10])

**Answer:**

In [ ]:
A[1] == A[1, :], which will use the given index to select that row, and then print all elements in that row. So [1] will give all elements in the second row. 
A[:,1] would give all elements in the first column. 

### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [7]:
A

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15]])

In [8]:
for i in A:
    print(i)

[1 2 3 4 5]
[ 6  7  8  9 10]
[11 12 13 14 15]


In [9]:
print('To iterate through an array elementwise, we can use the .flat attribute to make a flattened (1 dimensional) array.') 
for _ in A.flat:
    print(_)

To iterate through an array elementwise, we can use the .flat attribute to make a flattened (1 dimensional) array.
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [21]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


In [25]:
print('The code generates a 1-D array (a) which contains 30 elements, \nthen it is reshaped into "b" which has 2 blocks, 3 rows and the \nfinal paramter,"-1", tells numpy to calculate the final dimension to match \nthe number of elements (20/(2*3) = 5)')

The code generates a 1-D array (a) which contains 30 elements, 
then it is reshaped into "b" which has 2 blocks, 3 rows and the 
final paramter,"-1", tells numpy to calculate the final dimension to match 
the number of elements (20/(2*3) = 5)


# For the exercises below, read the document *"matematik_yh_antonio_vektorer_matriser_utdrag"*
# Solutions to the exercises and recorded videos can be found here: https://github.com/AntonioPrgomet/matematik_foer_yh

# If you find the exercises below very hard, do not worry. Try your best, that will be enough. 

### Broadcasting
**Read the following link about broadcasting: https://numpy.org/doc/stable/user/basics.broadcasting.html#basics-broadcasting**

# Remark on Broadcasting when doing Linear Algebra calculations in Python. 

### From the mathematical rules of matrix addition, the operation below (m1 + m2) does not make sense. The reason is that matrix addition requires two matrices of the same size. In Python however, it works due to broadcasting rules in NumPy. So you must be careful when doing Linear Algebra calculations in Python since they do not follow the "mathematical rules". This can however easily be handled by doing some simple programming, for example validating that two matrices have the same shape is easy if you for instance want to add two matrices. 

In [28]:
m1 = np.array([[1, 2], [3, 4]])
m2 = np.array([1, 1])
print(m1)
print()
print(m2)
print()
print(m1 + m2)

[[1 2]
 [3 4]]

[1 1]

[[2 3]
 [4 5]]


### The example below would also not be allowed if following the "mathematical rules" in Linear Algebra. But it works due to broadcasting in NumPy. 

In [29]:
v1 = np.array([1, 2, 3])
print(v1 + 1)

[2 3 4]


In [30]:
A = np.arange(1, 5).reshape(2,2)
print(A)

b = np.array([2, 2])
print(b)

[[1 2]
 [3 4]]
[2 2]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

In [39]:
import numpy as np
def add_mult_matrices(m1, m2, operation):
    if not isinstance(m1, np.ndarray) or not isinstance(m2, np.ndarray):
        raise ValueError('Only matrices are permitted')
    if operation not in  ['add', 'multiply']:
        raise ValueError('Operation must be either "add" or "multiply"')

    if operation == 'add':
        if m1.shape != m2.shape:
            raise ValueError('Matrices must be of the same shape')
        else:
            return m1 + m2

    elif operation == 'multiply':
        if m1.shape[1] != m2.shape[0]:
          raise ValueError('Matrices must have compatible dimensions')
        else:
            return m1 @ m2

m1 = np.array([[1,2], [3,4]])
m2 = np.array([[5,6], [7,8]])

result_add = add_mult_matrices(m1, m2, 'add')
print (result_add)
result_multiply = add_mult_matrices(m1, m2, 'multiply')
print (result_multiply)

[[ 6  8]
 [10 12]]
[[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

In [10]:
x = np.array([4,3])
print('Uppgift 10.1.1')
print('a',x.shape)
print('b',5*x)
print('c',3*x)
print('d',5*x + 3*x)
print('e',8*x)
print('f',4*x - x)
print('g_1',x.T)
print('g_2',x.T.shape)
print('h. It is defined because it is the same value, as x is a 1D vector.')
norm_x = np.linalg.norm(x)
print('i',norm_x)

Uppgift 10.1.1
a (2,)
b [20 15]
c [12  9]
d [32 24]
e [32 24]
f [12  9]
g_1 [4 3]
g_2 (2,)
h. It is defined because it is the same value, as x is a 1D vector.
i 5.0


In [72]:
v = np.array([[3], [7], [0],[11]])
print('Uppgift 10.1.2')
print('a',v.shape)
print('b',2*v)
print('d',5*v+2*v)
print('d',4*v - 2*v)
print('e_1',v.T)
print('e_2',v.T.shape)
v_norm = np.linalg.norm(v)
print('f',v_norm)

Uppgift 10.1.2
a (4, 1)
b [[ 6]
 [14]
 [ 0]
 [22]]
d [[21]
 [49]
 [ 0]
 [77]]
d [[ 6]
 [14]
 [ 0]
 [22]]
e_1 [[ 3  7  0 11]]
e_2 (1, 4)
f 13.379088160259652


In [73]:
v1 = np.array([[4,3,1,5]])
v2 = np.array([[2,3,1,1]])
print('Uppgift 10.1.3')
v1_norm = np.linalg.norm(v1)
v_product= np.linalg.norm(v1-v2)
print('a',v1_norm)
print('b',v_product)

Uppgift 10.1.3
a 7.14142842854285
b 4.47213595499958


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

In [12]:
print('Uppgift 10.2.1')
A = np.array([[2,1,-1],[1,-1,1]])
B = np.array([[4,-2, 1],[2,-4, -2]])
C = np.array([[1,2],[2,1]])
D = np.array([[3,4],[4,3]])
E = np.array([[1],[2]])
I = np.array([[1,0],[0,1]])
print('all matrices')
print(A)
print(B)
print(C)
print(D)
print(E)
print(I)

print('a')
print(2*A)
print('b')
print(B-2*A)
print('c')
print(3*C- 2*E)
print('d')
print(2*D- 3*C)
print('e')
print(D.T- 2*D)
print('f')
print(2*C.T - 2*D.T)
#print('g')
#print(A.T- B)
print('h')
#print(A@C)
print('i')
print(C@D)
print('j')
print(C@B)
print('k')
print(C@I)
print('l')
print(A@B.T)



Uppgift 10.2.1
all matrices
[[ 2  1 -1]
 [ 1 -1  1]]
[[ 4 -2  1]
 [ 2 -4 -2]]
[[1 2]
 [2 1]]
[[3 4]
 [4 3]]
[[1]
 [2]]
[[1 0]
 [0 1]]
a
[[ 4  2 -2]
 [ 2 -2  2]]
b
[[ 0 -4  3]
 [ 0 -2 -4]]
c
[[ 1  4]
 [ 2 -1]]
d
[[3 2]
 [2 3]]
e
[[-3 -4]
 [-4 -3]]
f
[[-4 -4]
 [-4 -4]]
h
i
[[11 10]
 [10 11]]
j
[[  8 -10  -3]
 [ 10  -8   0]]
k
[[1 2]
 [2 1]]
l
[[5 2]
 [7 4]]


In [9]:
A = np.array([[2,3,4],[5,4,1]])

print (A@A.T)

[[29 26]
 [26 42]]


In [18]:
A = np.array([[1,2],[2,4]])
B = np.array([[2,1],[1,3]])
C = np.array([[4,3],[0,2]])
print('Uppgift 10.2.3')
print('AB = AC')
print(A@B)
print(A@C)
print('B != C')
print(B)
print(C)

Uppgift 10.2.3
AB = AC
[[ 4  7]
 [ 8 14]]
[[ 4  7]
 [ 8 14]]
B != C
[[2 1]
 [1 3]]
[[4 3]
 [0 2]]


### Copies and Views
Read the following link: https://numpy.org/doc/stable/user/basics.copies.html

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [82]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)
np.may_share_memory(v1, v2)

[0 1 2 3]
[2 3]


True

In [76]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [77]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]
